OUTPUT_DIR: output/vidstg/
DATA_DIR: data/vidstg
TENSORBOARD_DIR: output/vidstg/tensorboard

INPUT:
  RESOLUTION: 420
  FLIP_PROB_TRAIN: 0.7
  TEMP_CROP_PROB: 0.5
  TRAIN_SAMPLE_NUM: 64

MODEL:
  WEIGHT: checkpoints/pretrained/pretrained_resnet101_checkpoint.pth
  WEIGHT_EVAL: checkpoints/grounding/vidstg.pth
  VISION_BACKBONE:
    NAME: resnet101
    POS_ENC: sine
  VIDEO_SWIN:
    MODEL_NAME: video_swin_t_p4w7
    PRETRAINED: video_swin_t_p4w7_k400_1k
    FEATURE_DIM: 768
    FREEZE: True
  TEXT_MODEL:
    NAME: roberta-base
  VSTG:
    FROM_SCRATCH: True
    USE_LEARN_TIME_EMBED: False
    USE_ACTION: True

DATASET:
  NAME: VidSTG
  APP_NUM: 20
  MOT_NUM: 34

DATALOADER:
  NUM_WORKERS: 8
  ASPECT_RATIO_GROUPING: False

SOLVER:
  MAX_EPOCH: 1
  BATCH_SIZE: 1
  BBOX_COEF: 5
  GIOU_COEF: 3
  TEMP_COEF: 2
  ATTN_COEF: 1
  CONF_COEF: 1
  CONF2_COEF: 1
  CONF3_COEF: 1
  CONF4_COEF: 1
  ACTIONESS_COEF: 2
  EOS_COEF: 0.3
  SIGMA: 2.0
  BASE_LR: 2e-4
  TEXT_LR: 5e-5
  VERB_LR: 3e-4
  VIS_BACKBONE_LR: 1e-5
  TEMP_LR: 2e-4
  OPTIMIZER: adamw
  VAL_PERIOD: 5000
  CHECKPOINT_PERIOD: 1000
  SHUFFLE: True
  SCHEDULE:
    TYPE: multistep_with_warmup_all
    DROP_STEP: [9,11]
  PRE_VAL: False
